Add test case for SoulClientRegisterService of soul-admin #507
dromara/soul pull request #565
Opened 2020-12-05 09:56 UTC by sakiila

Make sure that:

- [x] You have read the [contribution guidelines](https://dromara.org/en-us/docs/soul/contributor.html).
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] Your local test passed `mvn clean install -Dmaven.javadoc.skip=true`.

2020-12-05 11:08 UTC, dengliming requested changes

2020-12-05 11:08 UTC, dengliming commented on soul-admin/src/test/java/org/dromara/soul/admin/service/SoulClientRegisterServiceTest.java
> +        given(soulClientRegisterService.registerSpringMvc(any())).willReturn(SoulResultMessage.SUCCESS);
You can also mock metaDataMapper and eventPublisher to test more scenarios. Thanks.

2020-12-06 04:53 UTC, sakiila reviewed
Add test case for SoulClientRegisterService of soul-admin

2020-12-07 03:03 UTC, yu199195 approved these changes

2020-12-07 03:04 UTC, merged