test: add the test case for org.dromara.soul.plugin.sync.data.webosck…
dromara/soul pull request #588
Opened 2020-12-06 14:14 UTC by cocoZwwang

…et.handler.AuthDataHandler

Make sure that:

- [ ] You have read the [contribution guidelines](https://dromara.org/en-us/docs/soul/contributor.html).
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] Your local test passed `mvn clean install -Dmaven.javadoc.skip=true`.

2020-12-06 14:24 UTC, songyuequan requested changes

2020-12-06 14:24 UTC, songyuequan commented on soul-sync-data-center/soul-sync-data-websocket/src/test/java/org/dromara/soul/plugin/sync/data/weboscket/handler/AuthDataHandlerTest.java
> +public class AuthDataHandlerTest {
add final on the test class

2020-12-06 14:45 UTC, cocoZwwang commented on soul-sync-data-center/soul-sync-data-websocket/src/test/java/org/dromara/soul/plugin/sync/data/weboscket/handler/AuthDataHandlerTest.java
> +public class AuthDataHandlerTest {
OK! I've modified and submitted.

2020-12-07 01:31 UTC, tydhot approved these changes
the code annotation is cool!

2020-12-07 01:32 UTC, merged

2020-12-07 05:03 UTC, cocoZwwang commented
> the code annotation is cool!

Thanks!