Eliminate the number of code warnings in the IDE.
dromara/soul pull request #812
Opened 2020-12-18 17:14 UTC by Zhoutzzz

// Describe your PR here; eg. Fixes #issueNo

When use IDEA open project, some .java files had a little of warning, I try to eliminate the warnings in these files.

Make sure that:

- [ ] You have read the [contribution guidelines](https://dromara.org/en-us/docs/soul/contributor.html).
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] Your local test passed `mvn clean install -Dmaven.javadoc.skip=true`.

2020-12-19 05:22 UTC, dengliming requested changes

2020-12-19 05:22 UTC, dengliming commented on soul-client/soul-client-dubbo/soul-client-dubbo-common/src/main/java/org/dromara/soul/client/dubbo/common/dto/DubboRpcExt.java
> +    private String loadBalance;
revert it.

2020-12-19 05:22 UTC, dengliming commented on soul-common/src/main/java/org/dromara/soul/common/constant/DubboParamConstants.java
> +    public static final String LOAD_BALANCE = "loadBalance";
revert it

2020-12-20 02:16 UTC, yu199195 approved these changes

2020-12-20 02:25 UTC, merged