Improve code coverage for PluginServiceImpl in soul-admin
dromara/soul pull request #814
Opened 2020-12-19 06:43 UTC by midnight2104

// Describe your PR here; eg. Fixes #issueNo
Fixes 802,  improve code coverage for PluginServiceImpl from 80% to 100% in soul-admin.

Make sure that:

- [ ] You have read the [contribution guidelines](https://dromara.org/en-us/docs/soul/contributor.html).
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] Your local test passed `mvn clean install -Dmaven.javadoc.skip=true`.

2020-12-19 09:28 UTC, dengliming requested changes

2020-12-19 09:28 UTC, dengliming commented on soul-admin/src/main/resources/application-local.yml
>      driver-class-name: com.mysql.jdbc.Driver
revert

2020-12-20 02:39 UTC, midnight2104 commented on soul-admin/src/main/resources/application-local.yml
>      driver-class-name: com.mysql.jdbc.Driver
got it

2020-12-20 02:42 UTC, yu199195 approved these changes

2020-12-20 02:54 UTC, merged